### ISSUE TITLE
Dataset Download Issue

### ISSUE THREAD

**Issue by ivam-he** [Juanhui28/HeaRT#1]
Dear Juanhui28,

I encountered an issue when running the command `bash download_data.sh`. The problem appears to be as follows:
`
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now`

Additionally, when attempting to execute the command `wget https://cse.msu.edu/~shomerha/HeaRT-Data/dataset.tar.gz`, I received a "404 Not Found" error.

Could you please assist me in resolving these issues?

Thank you!

**Comment by Juanhui28** [comment]
Thanks for letting us know. It should be fixed now. Feel free to let me
know if you have any other issues.

Best,
Juanhui
Mingguo He ***@***.***> 于2023年11月28日周二 09:39写道：

**Comment by ivam-he** [comment]
Okay, thanks!
