### ISSUE TITLE
PyG not successfully installed using the yaml

### ISSUE THREAD

**Issue by jwzhi** [Juanhui28/HeaRT#3]
I installed PyG and related packages using `conda env create -f heart_env.yml `, as suggested in the installation guide. 

However, it would return ` 1472580 abort (core dumped)` when trying `from torch_geometric.nn import GCNConv, SAGEConv, GINConv, GATConv` in gnn_model.py

Is there any insight on how to fix the installation? Is there any specific pyg packages that would fail when installing all of them from conda directly?

**Comment by Juanhui28** [comment]
Thanks for your interest!

If you encounter any difficulties using conda, I kindly suggest referring to the PyG installation guide available on their [official website](https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html). For your reference, our current environment includes:
- python: 3.9
- torch: 1.12.1
- torch cuda: 11.6

according to the installation guide of pyg, we can use the following command: 
`TORCH=1.12.1`
`CUDA=cu116`
`pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html`

please feel free to let me know if you have any concerns
