### ISSUE TITLE
Where can I find the missing modules?

### ISSUE THREAD

**Issue by yuhaoxu99** [Juanhui28/HeaRT#4]
I think there are some modules are missed, such as evalutors, gnn_model and utils, right? So where can I find these modules to make the project run successfully.

**Comment by Juanhui28** [comment]
Hi there,

Thanks for your interest. The `evalutors.py`, `gnn_model.py`, `utils.py` are in the benchmarking folder.

**Comment by yuhaoxu99** [comment]
> Hi there,
> 
> Thanks for your interest. The `evalutors.py`, `gnn_model.py`, `utils.py` are in the benchmarking folder.

Thank you for your kind reply! I have successfully found the modules.
